let mappingArr = [[ 'Agostino Accorimboni', 'Agostino Accorimboni' ],
[ 'André Cardinal Destouches', 'André Cardinal Destouches' ],
[ 'André-Ernest-Modeste Grétry',
  'André-Ernest-Modeste Grétry',
, 'Grétry;, André Grétry' ],
[ 'Anton Eberl', 'Anton Eberl', 'Eberl' ],
[ 'Anton Schweitzer', 'Anton Schweitzer', 'Schweitzer' ],
[ 'Antonín Volánek', 'Antonín Volánek', 'Volánek' ],
[ 'Antonio Bianchi', 'Antonio Bianchi', 'Bianchi' ],
[ 'Antonio Casimir Cartellieri',
  'Antonio Casimir Cartellieri',
, 'Cartellieri' ],
[ 'Antonio Sacchini', 'Antonio Sacchini', 'Sacchini' ],
[ 'Antonio Salieri', 'Antonio Salieri', 'Salieri' ],
[ 'Antonio Vivaldi', 'Antonio Vivaldi', 'Vivaldi' ],
[ 'Apostolo Zeno', 'Apostolo Zeno', 'Zeno' ],
[ 'Benedikt Schack', 'Benedikt Schack', 'Schack' ],
[ 'Bertati', 'Bertati'],
[ 'Benucci', 'Benucci'],
[ 'Weigl', 'Weigl'],
[ 'Carl Bernhard Wessely', 'Carl Bernhard Wessely', 'Wessely', 'Carl Wessely' ],
[ 'Carl David Stegmann', 'Carl David Stegmann', 'Stegmann', 'Carl Stegmann' ],
[ 'Carl Ditters', 'Carl Ditters', 'Ditters' ],
[ 'Carl Gottlieb Doebbelin', 'Carl Gottlieb Doebbelin', 'Doebbelin', 'Carl Doebbelin', 'Carl Gottlieb' ],
[ 'Carl Sigmund Schönebeck', 'Carl Sigmund Schönebeck', 'Schönebeck', 'Carl Schönebeck' ],
[ 'Caspar Hellmich', 'Caspar Hellmich', 'Hellmich' ],
[ 'Caspar Wilhelm von Borcke', 'Caspar Wilhelm von Borcke', 'Borcke', 'von Borcke', 'Caspar von Borcke', 'Caspar Borcke' ],
[ 'Charles Batteux', 'Charles Batteux', 'Batteux' ],
[ 'Charles de Marguetel de Saint-Évremond',
,
  'Charles de Marguetel de Saint-Évremond', 'Charles de Marguetel', 'Saint-Évremond', 'Charles de Saint-Évremond' ],
[ 'Charles Dibdin', 'Charles Dibdin', 'Dibdin' ],
[ 'Christian Gottlob Neefe', 'Christian Gottlob Neefe', 'Neefe', 'Christian Neefe' ],
[ 'Christian Ludwig Dieter', 'Christian Ludwig Dieter', 'Dieter', 'Christian Dieter' ],
[ 'Christoph Willibald Gluck',
  'Christoph Willibald Gluck',
  'Christoph Willibald Gluck', 'Gluck', 'Christoph Gluck' ],
[ 'Colley Cibber', 'Colley Cibber', 'Cibber' ],
[ 'Crequi', 'Crequi' ],
[ 'de Vasseur', 'de Vasseur', 'Vasseur' ],
[ 'Domenico Cimarosa', 'Domenico Cimarosa', 'Cimarosa' ],
[ 'Egidio Romualdo Duni', 'Egidio Romualdo Duni', 'Duni' ],
[ 'Emanuel Schikaneder',
  'Emanuel Schikaneder',
  'Emanuel Schikaneder', 'Schikaneder' ],
[ 'Ernst Wilhelm Wolf', 'Ernst Wilhelm Wolf', 'Wolf' ],
[ 'Etienne Nicolas Méhul', 'Etienne Nicolas Méhul', 'Méhul' ],
[ 'Ferdinand Fränzl', 'Ferdinand Fränzl', 'Fränzl' ],
[ 'Ferdinand Kauer', 'Ferdinand Kauer', 'Kauer' ],
[ 'Ferdinando Paer', 'Ferdinando Paer', 'Paer' ],
[ 'Florian Gassmann', 'Florian Gassmann', 'Gassmann' ],
[ 'Francesco Bianchi', 'Francesco Bianchi', 'Bianchi' ],
[ 'François l\'Hermite', 'François l\'Hermite', 'L\'Hermite', 'Lhermite' ],
[ 'François-André Danican Philidor',
  'François-André Danican Philidor',
, 'Philidor' ],
[ 'František Adam Míča', 'František Adam Míča', 'Míča', 'František Míča' ],
[ 'Franz Anton', 'Franz Anton' ],
[ 'Franz Anton Hoffmeister', 'Franz Anton Hoffmeister', 'Hoffmeister', 'Franz Hoffmeister' ],
[ 'Franz Seydelmann', 'Franz Seydelmann', 'Seydelmann' ],
[ 'Franz Stanislaus Spindler', 'Franz Stanislaus Spindler', 'Spindler', 'Franz Spindler' ],
[ 'Franz Xaver Huber', 'Franz Xaver Huber', 'Huber' ],
[ 'Franz Xaver Süssmayr',
  'Franz Xaver Süssmayr',
  'Franz Xaver Süßmayr', 'Süßmayr', 'Süssmayr' ],
[ 'Friederike Caroline Neuber',
,
  'Friederike Caroline Neuber', 'Neuber' ],
[ 'Friedrich II', 'Friedrich II' ],
[ 'Friedrich Koch', 'Friedrich Koch', 'Kock' ],
[ 'Friedrich Ludwig Aemilius', 'Friedrich Ludwig Aemilius', 'Aemilius', 'Friedrich Aemilius' ],
[ 'Friedrich Ludwig Benda', 'Friedrich Ludwig Benda', 'Benda' ],
[ 'Gaetano Brunati', 'Gaetano Brunati', 'Brunati' ],
[ 'Gaetano Pugnani', 'Gaetano Pugnani', 'Pugnani' ],
[ 'Gennaro Astarita', 'Gennaro Astarita', 'Astarita' ],
[ 'Georg Anton Kreußer', 'Georg Anton Kreußer', 'Kreußer' ],
[ 'Georg Benda', 'Georg Benda', 'Benda' ],
[ 'Giacomo Tritto', 'Giacomo Tritto', 'Tritto' ],
[ 'Giovanni Battista Borghi', 'Giovanni Battista Borghi', 'Borghi' ],
[ 'Giovanni Paisiello', 'Giovanni Paisiello', 'Paisiello' ],
[ 'Giuseppe Gazzaniga', 'Giuseppe Gazzaniga', 'Gazzaniga' ],
[ 'Giuseppe Sarti', 'Giuseppe Sarti', 'Sarti' ],
[ 'Henri Larrivée', 'Henri Larrivée', 'Larrivée', 'L\'arrivée', 'Larrivee', 'L\'arrivee' ],
[ 'Holzinger', 'Holzinger' ],
[ 'Hugo Franz Freiherr von Kerpen',
  'Hugo Franz Freiherr von Kerpen',
, 'von Kerpen', 'Kerpen' ],
[ 'Ignaz Schuster and Wenzel Müller',
  'Ignaz Schuster and Wenzel Müller',
 ],
[ 'Ignaz Umlauf', 'Ignaz Umlauf', 'Umlauf' ],
[ 'Ignaz Walter', 'Ignaz Walter (the older)', 'Walter' ],
[ 'Jean Baptiste Lemoyne', 'Jean Baptiste Lemoyne', 'Lemoyne' ],
[ 'Jean Baptiste Lully', 'Jean Baptiste Lully', 'Lully' ],
[ 'Jean de Vert', 'Jean de Vert', 'Vert', 'de Vert' ],
[ 'Jean-Jacques Rousseau',
  'Jean-Jacques Rousseau',
  'Jean Jacques Rousseau', 'Rousseau' ],
[ 'Jean Joseph Cassanéa de Mondonville',
,
  'Jean Joseph Cassanéa de Mondonville', 'Mondonville', 'Jean Joseph Cassanéa', 'Cassanéa' ],
[ 'Jean Philippe Rameau', 'Jean Philippe Rameau', 'Rameau' ],
[ 'Jean-François Marmontel', 'Jean-François Marmontel', 'Marmontel' ],
[ 'Jean-Paul-Égide Martini', 'Jean-Paul-Égide Martini', 'Martini' ],
[ 'Jean-Paul-Gilles Martini', 'Jean-Paul-Gilles Martini', 'Martini' ],
[ 'Johann Abraham Peter Schulz',
  'Johann Abraham Peter Schulz',
, 'Schulz', 'Johann Schulz' ],
[ 'Johann Adam Hiller', 'Johann Adam Hiller', 'Hiller', 'Johann Hiller' ],
[ 'Johann Adolf Hasse', 'Johann Adolf Hasse', 'Hasse' ],
[ 'Johann André', 'Johann André', 'Johann André', 'André' ],
[ 'Johann Appelt', 'Johann Appelt', 'Appelt' ],
[ 'Johann Baptist Paneck', 'Johann Baptist Paneck', 'Paneck' ],
[ 'Johann Christoph Kaffka', 'Johann Christoph Kaffka', 'Kaffka', 'Johann Kaffka' ],
[ 'Johann Christoph Pepusch', 'Johann Christoph Pepusch', 'Pepusch' ],
[ 'Johann Christoph von Zabuesnig',
  'Johann Christoph von Zabuesnig',
, 'von Zabuesnig', 'Zabuesnig' ],
[ 'Johann Friedrich Hönicke', 'Johann Friedrich Hönicke', 'Hönicke' ],
[ 'Johann Friedrich Reichardt',
  'Johann Friedrich Reichardt',
, 'Reichardt' ],
[ 'Johann Gottlieb Naumann', 'Johann Gottlieb Naumann', 'Naumann' ],
[ 'Johann Henneberg', 'Johann Henneberg', 'Henneberg' ],
[ 'Johann Lasser', 'Johann Lasser', 'Lasser' ],
[ 'Johann Schenk', 'Johann Schenk', 'Schenk' ],
[ 'Johann Simon Mayr', 'Johann Simon Mayr', 'Mayr' ],
[ 'John Gay', 'John Gay', 'Gay' ],
[ 'Josef Martin Ruprecht', 'Josef Martin Ruprecht', 'Ruprecht' ],
[ 'Joseph Haydn', 'Joseph Haydn', 'Haydn' ],
[ 'Joseph Legros', 'Joseph Legros', 'Legros' ],
[ 'Joseph Schuster', 'Joseph Schuster', 'Schuster' ],
[ 'Joseph Weigl', 'Joseph Weigl', 'Weigl' ],
[ 'Joseph Wölfl', 'Joseph Wölfl', 'Wölfl' ],
[ 'Karl Friedrich Hensler', 'Karl Friedrich Hensler', 'Hensler', 'Friedrich Hensler' ],
[ 'Luigi Bologna', 'Luigi Bologna', 'Bologna' ],
[ 'Luigi Cherubini', 'Luigi Cherubini', 'Cherubini' ],
[ 'Lycoris', 'Lycoris' ],
[ 'Macello da Capua', 'Macello da Capua', 'Capua', 'de Capua' ],
[ 'Marcos Portogallo', 'Marcos Portogallo', 'Portogallo' ],
[ 'Marie-Josèphe La Guerre', 'Marie-Josèphe La Guerre', 'La Guerre' ],
[ 'Michel-Jean Sedaine', 'Michel-Jean Sedaine', 'Sedaine' ],
[ 'Myrtil', 'Myrtil' ],
[ 'Niccolò Antonio Zingarelli',
  'Niccolò Antonio Zingarelli',
, 'Zingarelli' ],
[ 'Niccolò Piccinni', 'Niccolò Piccinni', 'Niccolò Piccini', 'Piccini', 'Piccinni' ],
[ 'Nicolas Boileau', 'Nicolas Boileau', 'Boileau' ],
[ 'Nicolas Dalayrac', 'Nicolas Dalayrac', 'Dalayrac' ],
[ 'Nicolas Dezède', 'Nicolas Dezède', 'Dezède' ],
[ 'Otto Carl Erdmann Freiherr von Kospoth',
  'Otto Carl Erdmann Freiherr von Kospoth',
, 'Kospoth', 'von Kospoth' ],
[ 'Pasquale Anfossi', 'Pasquale Anfossi', 'Pasquale Anfossi', 'Anfossi' ],
[ 'Paul Wranitzky', 'Paul Wranitzky', 'Wranitzky' ],
[ 'Peter Ritter', 'Peter Ritter', 'Ritter' ],
[ 'Peter von Winter', 'Peter von Winter', 'Winter' ],
[ 'Philippe Quinault', 'Philippe Quinault', 'Quinault' ],
[ 'Pierre Dutillieu', 'Pierre Dutillieu', 'Dutillieu' ],
[ 'Pierre Gaveaux', 'Pierre Gaveaux', 'Gaveaux' ],
[ 'Pierre Perrin', 'Pierre Perrin', 'Perrin' ],
[ 'Pierre-Alexandre Monsigny',
  'Pierre-Alexandre Monsigny',
  'Pierre Alexandre Monsigny', 'Monsigny' ],
[ 'Pietro Alessandro Guglielmi',
  'Pietro Alessandro Guglielmi',
, 'Guglielmi' ],
[ 'Pietro Cesti', 'Pietro Cesti', 'Cesti' ],
[ 'Pietro Metastasio', 'Pietro Metastasio', 'Metastasio' ],
[ 'Quintus Flaccus Horatius (Horaz)',
,
  'Quintus Flaccus Horatius (Horaz)', 'Horatius', 'Horaz' ],
[ 'Rameau', 'Rameau' ],
[ 'Rauer', 'Rauer' ],
[ 'Reymann', 'Reymann' ],
[ 'Robert Cambert', 'Robert Cambert', 'Cambert' ],
[ 'Rodolphe Kreutzer', 'Rodolphe Kreutzer', 'Kreutzer' ],
[ 'Schack and Gerl', 'Schack and Gerl' ],
[ 'Siefeke', 'Siefeke' ],
[ 'Silvestro de Palma', 'Silvestro de Palma', 'Palma' ],
[ 'Sophie Arnoud', 'Sophie Arnoud', 'Arnoud' ],
[ 'Sophie Marie Niclas', 'Sophie Marie Niclas' , 'Niclas'],
[ 'Stanislas Spindler', 'Stanislas Spindler', 'Spindler' ],
[ 'Stanislaus de Champein', 'Stanislaus de Champein', 'Champein' ],
[ 'Stephen Storace', 'Stephen Storace' , 'Storace'],
[ 'Thaddäus Weigl', 'Thaddäus Weigl' , 'Weigl'],
[ 'Valentino Fioravanti', 'Valentino Fioravanti' , 'Fioravanti'],
[ 'Vassee', 'Vassee' ],
[ 'Vicente Martín y Soler', 'Vicente Martín y Soler' , 'Soler'],
[ 'Vincenz Franz Tuczek', 'Vincenz Franz Tuczek' , 'Tuczek'],
[ 'Vincenzo Righini', 'Vincenzo Righini', 'Righini' ],
[ 'Virginie', 'Virginie' ],
[ 'Wenzel Müller', 'Wenzel Müller', 'Müller' ],
[ 'Wolfgang Amadeus Mozart',
  'Wolfgang Amadeus Mozart',
  'Wolfgang Amadé Mozart', 'Mozart' ]]

let canonIt = (name) => {
  for (let i = 0; i < mappingArr.length; i++) {
    
    if (mappingArr[i].includes(name)) {
      // if (mappingArr[i])
      return mappingArr[i][0]
    }
  }
}

//
let nameSearch = 'Müller'

console.log(canonIt(nameSearch))

